---
- name: Create Marathon conf file
  file:
    path: /etc/default/marathon
    mode: 0755
    state: touch

- name: Set ENV variables
  lineinfile:
    path: /etc/default/marathon
    regexp: '^{{ item }}$'
    line: '{{item}}'
  with_items: "{{ marathon_env_vars }}"

- name: Set required --master option
  lineinfile:
    path: /etc/default/marathon
    regexp: '^MARATHON_MASTER='
    line: 'MARATHON_MASTER="{{ mesos_zookeeper_masters }}"'

- name: Set optional --zk option
  lineinfile:
    path: /etc/default/marathon
    regexp: '^MARATHON_ZK='
    line: 'MARATHON_ZK="{{ marathon_zookeeper_state }}"'

- name: Set --hostname option
  lineinfile:
    path: /etc/default/marathon
    regexp: '^MARATHON_HOSTNAME='
    line: 'MARATHON_HOSTNAME="{{ marathon_hostname }}"'

- name: Set --http-port option
  lineinfile:
    path: /etc/default/marathon
    regexp: '^MARATHON_HTTP_PORT='
    line: 'MARATHON_HTTP_PORT="{{ marathon_port }}"'

- name: Set additional options
  lineinfile:
    path: /etc/default/marathon
    regexp: '^MARATHON_{{ item.name|upper }}='
    line: 'MARATHON_{{ item.name|upper }}="{{ item.value }}"'
  with_items: "{{ marathon_additional_configs }}"
  tags:
    - config-additional